version: "3.9"

services:
  converter:
    build: ./converter
    image: converter:latest
    volumes:
      - /srv/shared:/data/shared:rw,exec
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    environment:
      # --- Connexion Postgres Supabase ---
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}

      # --- Sécurité / fuseaux ---
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Paris}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

      # --- Import automatique au 1ᵉʳ start ---
      - N8N_IMPORT_EXPORT_DIR=/backup
      - N8N_IMPORT_EXPORT_OVERWRITE=overwrite
    entrypoint: >
      /bin/sh -c "
        n8n import:credentials --separate --input /backup/credentials || true &&
        n8n import:workflow    --separate --input /backup/workflows   || true &&
        n8n start
      "
    volumes:
      - /srv/n8n_backup:/backup:rw                     
      - /srv/shared:/data/shared:rw,exec
      - /srv/n8n_data:/home/node/.n8n:rw,exec
    ports:
      - "5678"          # exposé ensuite via Traefik/Coolify
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10

  n8n-backup:
    image: n8nio/n8n:latest
    user: "node"
    depends_on: [n8n]
    environment:
      # réemploi des variables DB_* déjà déclarées dans l’UI
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}     
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Paris}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - /srv/n8n_backup:/backup:rw,exec
      - /srv/n8n_data:/home/node/.n8n:rw,exec
    entrypoint: >
      /bin/sh -c '
        while true; do
          n8n export:workflow    --backup --output /backup/workflows   &&
          n8n export:credentials --backup --output /backup/credentials &&
          pg_dump --dbname=postgresql://${DB_POSTGRESDB_USER}:${DB_POSTGRESDB_PASSWORD}@${DB_POSTGRESDB_HOST}:${DB_POSTGRESDB_PORT}/${DB_POSTGRESDB_DATABASE} \
                  --file=/backup/pgdump/n8n-$(date +%F-%H%M).sql &&
          sleep 300;
        done
      '
